// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.4.1
// LVGL version: 8.3.11
// Project name: SquareLine_Project

#include "ui.h"

static lv_chart_series_t *temp_series;
static lv_chart_series_t *humid_series;

void ui_Screen2_screen_init(void)
{
    ui_Screen2 = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_Screen2, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Panel2 = lv_obj_create(ui_Screen2);
    lv_obj_set_width(ui_Panel2, 78);
    lv_obj_set_height(ui_Panel2, 49);
    lv_obj_set_x(ui_Panel2, 0);
    lv_obj_set_y(ui_Panel2, -105);
    lv_obj_set_align(ui_Panel2, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_Panel2, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Label7 = lv_label_create(ui_Panel2);
    lv_obj_set_width(ui_Label7, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label7, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label7, 0);
    lv_obj_set_y(ui_Label7, -2);
    lv_obj_set_align(ui_Label7, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label7, "Back");

    ui_chart = lv_chart_create(ui_Screen2);
    lv_obj_set_width(ui_chart, 240);
    lv_obj_set_align(ui_chart, LV_ALIGN_CENTER);
    lv_obj_set_height(ui_chart, 150);
    lv_obj_set_y(ui_chart, 40);

    temp_series = lv_chart_add_series(ui_chart, lv_palette_main(LV_PALETTE_RED), LV_CHART_AXIS_PRIMARY_Y);
    humid_series = lv_chart_add_series(ui_chart, lv_palette_main(LV_PALETTE_BLUE), LV_CHART_AXIS_PRIMARY_Y);

    lv_chart_set_axis_tick(ui_chart, LV_CHART_AXIS_PRIMARY_Y, 10, 5, 6, 2, true, 50);
    lv_chart_set_axis_tick(ui_chart, LV_CHART_AXIS_PRIMARY_Y, 10, 5, 9, 2, true, 50);

    // add labels
    lv_obj_t *temp_axis_label = lv_label_create(ui_Screen2);
    lv_label_set_text(temp_axis_label, "Temperature (C)");
    lv_obj_align(temp_axis_label, LV_ALIGN_OUT_TOP_LEFT, 10, 40);
    lv_obj_t *humid_axis_label = lv_label_create(ui_Screen2);
    lv_label_set_text(humid_axis_label, "Humidity (%)");
    lv_obj_align(humid_axis_label, LV_ALIGN_OUT_BOTTOM_LEFT, 10, 60);

    //temp line label
    lv_obj_t *temp_line_label = lv_label_create(ui_Screen2);
    lv_label_set_text(temp_line_label, "|");
    lv_obj_align(temp_line_label, LV_ALIGN_OUT_TOP_LEFT, 5, 40);
    //temp style
    static lv_style_t style;
    lv_style_init(&style);
    lv_style_set_text_color(&style, lv_color_hex(0x26C4A1)); // Set text color to green
    //hum line label
    lv_obj_t *hum_line_label = lv_label_create(ui_Screen2);
    lv_label_set_text(hum_line_label, "|");
    lv_obj_align(hum_line_label, LV_ALIGN_OUT_BOTTOM_LEFT, 5, 60);  
    //hum style
    static lv_style_t stylehum;
    lv_style_init(&stylehum);
    lv_style_set_text_color(&stylehum, lv_color_hex(0x4040FF)); // Set text color to green
    // Apply the style to the label
    lv_obj_add_style(temp_line_label, &style, 0);
    lv_obj_add_style(hum_line_label, &stylehum, 0);

    //data for the chart
    lv_chart_set_point_count(ui_chart, 30);
    lv_chart_set_type(ui_chart, LV_CHART_TYPE_LINE);
    lv_obj_set_style_size(ui_chart, 0, LV_PART_INDICATOR);
    lv_chart_set_series_color(ui_chart, temp_series, lv_color_hex(0x26C4A1));

    lv_obj_add_event_cb(ui_Panel2, ui_event_Panel2, LV_EVENT_ALL, NULL);
}

void update_chart(float temperature, float humidity)
{
    // Memperbarui data pada chart
    static uint8_t data_index = 0;

    lv_chart_set_next_value(ui_chart, temp_series, temperature);
    lv_chart_set_next_value(ui_chart, humid_series, humidity);

    data_index = (data_index + 1) % 30; // Menggeser index data
}